export const chuteiras = [
    {
        url: "https://acdn.mitiendanube.com/stores/001/249/553/products/chuteira-campo-adidas-x-speedportal-1-2022-copa-do-mundo-verde-71-4ed50118161ef2b59b16738120554174-640-0.jpg",
        nome: "Adidas Speedportal.1",
        numero: 1,
        tipo: "Campo",
        informacao: "As chuteiras são suas aliadas no campo, proporcionando desempenho e estilo durante cada partida. Mas, como qualquer equipamento, elas precisam de cuidados para durar mais e te acompanhar em todas as jogadas.",
    },
    {
        url: "https://acdn.mitiendanube.com/stores/001/055/309/products/adidas-predator-edge-1-low-fg-qatar-nova-lancamento-chuteira-campo-original-importada-profissional-adulta-masculina-profissi-41-29561efbb3bb1861c216699350081524-1024-1024.jpg",
        nome: "Adidas Predator",
        numero: 2,
        tipo: "Campo",
        informacao: "As chuteiras são suas aliadas no campo, proporcionando desempenho e estilo durante cada partida. Mas, como qualquer equipamento, elas precisam de cuidados para durar mais e te acompanhar em todas as jogadas.",
    },
    {
        url: "https://acdn.mitiendanube.com/stores/001/055/309/products/chuteira-adidas-predator-fifa-world-cup-2022-qatar-campo-profissional-1linha-campo-original-comprar-preta-confiavel-31-f9bc1bbf02a6932d1c16795197533047-1024-1024.jpeg",
        nome: "Adidas Predator+Edge",
        numero: 3,
        tipo: "Campo",
        informacao: "As chuteiras são suas aliadas no campo, proporcionando desempenho e estilo durante cada partida. Mas, como qualquer equipamento, elas precisam de cuidados para durar mais e te acompanhar em todas as jogadas.",
    },
    {
        url: "https://www.lojadssports.com.br/cdn/shop/products/3a30367d_800x.jpg?v=1682212086",
        nome: "Adidas SpeedPortal 1.0",
        numero: 4,
        tipo: "Campo",
        informacao: "As chuteiras são suas aliadas no campo, proporcionando desempenho e estilo durante cada partida. Mas, como qualquer equipamento, elas precisam de cuidados para durar mais e te acompanhar em todas as jogadas.",
    },
    {
        url: "https://chuteiraspi.com/wp-content/uploads/2022/06/fb827122.jpg",
        nome: "Adidas SpeedFlow",
        numero: 5,
        tipo: "Campo",
        informacao: "As chuteiras são suas aliadas no campo, proporcionando desempenho e estilo durante cada partida. Mas, como qualquer equipamento, elas precisam de cuidados para durar mais e te acompanhar em todas as jogadas.",
        
    },
    {
        url: "https://acdn.mitiendanube.com/stores/001/805/503/products/139ea9241-6a74100e7e3e112bd416632117195533-640-0.jpg",
        nome: "Adidas Predator Edge 1",
        numero: 6,
        tipo: "Campo",
        informacao: "As chuteiras são suas aliadas no campo, proporcionando desempenho e estilo durante cada partida. Mas, como qualquer equipamento, elas precisam de cuidados para durar mais e te acompanhar em todas as jogadas.",
    },
    {
        url: "https://acdn.mitiendanube.com/stores/001/055/309/products/chuteira-nike-air-zoom-mercurial-superfly-ix-elite-campo-profissional-1linha-campo-original-comprar-branca-rosa-azul-botinha-cano-confiave-11-a1a6c970314c0e151116796088230561-1024-1024.jpg",
        nome: "Nike SuperFly 9",
        numero: 7,
        tipo: "Campo",
        informacao: "As chuteiras são suas aliadas no campo, proporcionando desempenho e estilo durante cada partida. Mas, como qualquer equipamento, elas precisam de cuidados para durar mais e te acompanhar em todas as jogadas.",
    },
    {
        url: "https://acdn.mitiendanube.com/stores/002/341/698/products/chuteira-campo-nike-air-zoom-mercurial-sg-cr7-2022-tevo-sports-31-124e49862fe80cd10216880667092381-1024-1024.jpg",
        nome: "Nike Air Zoom",
        numero: 8,
        tipo: "Campo",
        informacao: "As chuteiras são suas aliadas no campo, proporcionando desempenho e estilo durante cada partida. Mas, como qualquer equipamento, elas precisam de cuidados para durar mais e te acompanhar em todas as jogadas.",
    },
    {
        url: "https://www.cache2net2.com//Repositorio/8328/Produtos/b1aea23f-0.jpg?=1696728-1",
        nome: "Nike Super Fly",
        numero: 9,
        tipo: "Campo",
        informacao: "As chuteiras são suas aliadas no campo, proporcionando desempenho e estilo durante cada partida. Mas, como qualquer equipamento, elas precisam de cuidados para durar mais e te acompanhar em todas as jogadas.",
    },
    {
        url: "https://cdn.awsli.com.br/600x450/1842/1842028/produto/211027541/9c5e1c58-jbkncw.jpg",
        nome: "Nike SuperFly CR7",
        numero: 10,
        tipo: "Campo",
        informacao: "As chuteiras são suas aliadas no campo, proporcionando desempenho e estilo durante cada partida. Mas, como qualquer equipamento, elas precisam de cuidados para durar mais e te acompanhar em todas as jogadas.",
    },
    {
        url: "https://acdn.mitiendanube.com/stores/001/055/309/products/chuteira-nike-phantom-gx-elite-fg-2023-2024-branco-com-verde-profissional-1-linha-campo-original-oficial-birro-plastico-qualidade-gramado-grama-sintetica-natural-leve-lancamento-nova-7d309d78c0624ed34d17008500867191-1024-1024.jpeg",
        nome: "Nike Phatom GX",
        numero: 11,
        tipo: "Campo",
        informacao: "As chuteiras são suas aliadas no campo, proporcionando desempenho e estilo durante cada partida. Mas, como qualquer equipamento, elas precisam de cuidados para durar mais e te acompanhar em todas as jogadas.",
    },
    {
        url: "https://acdn.mitiendanube.com/stores/001/055/309/products/chuteira-nike-phantom-luna-elite-fg-azul-claro-com-verde-claro-profissional-1-linha-campo-original-oficial-birro-plastico-gramado-grama-sintetica-natural-lancamento-4-d1990b605882a18c8117023217236896-1024-1024.jpeg",
        nome: "Nike Phatom Luna",
        numero: 12,
        tipo: "Campo",
        informacao: "As chuteiras são suas aliadas no campo, proporcionando desempenho e estilo durante cada partida. Mas, como qualquer equipamento, elas precisam de cuidados para durar mais e te acompanhar em todas as jogadas.",
    },
];