export const chuteiras = [
    {
        url: "https://acdn.mitiendanube.com/stores/001/249/553/products/chuteira-campo-adidas-x-speedportal-1-2022-copa-do-mundo-verde-71-4ed50118161ef2b59b16738120554174-640-0.jpg",
        nome: "Adidas Speedportal.1",
        numero: 1,
        tipo: "Campo",
        titulo:"Leveza explosiva para você deixar a defesa para trás.",
        informacao: "A Chuteira Adidas X Speedportal é a arma secreta para você detonar no campo. Criada para jogadores que redefinem a velocidade, ela combina tecnologias inovadoras para te levar ao próximo nível.",
        avaliação:"4.9",
        vendidos:"256",
        preço:"309,80",
    },
    {
        url: "https://acdn.mitiendanube.com/stores/001/055/309/products/adidas-predator-edge-1-low-fg-qatar-nova-lancamento-chuteira-campo-original-importada-profissional-adulta-masculina-profissi-41-29561efbb3bb1861c216699350081524-1024-1024.jpg",
        nome: "Adidas Predator",
        numero: 2,
        tipo: "Campo",
        titulo:"Domine o campo com a Chuteira Adidas Predator",
        informacao: "Desperte o Predador em você. Assuma o controle total do jogo com a Predator, a chuteira da adidas que redefine o poder e a precisão.",
        avaliação:"4.7",
        vendidos:"301",
        preço:"356,90",
    },
    {
        url: "https://acdn.mitiendanube.com/stores/001/055/309/products/chuteira-adidas-predator-fifa-world-cup-2022-qatar-campo-profissional-1linha-campo-original-comprar-preta-confiavel-31-f9bc1bbf02a6932d1c16795197533047-1024-1024.jpeg",
        nome: "Adidas Predator+Edge",
        numero: 3,
        tipo: "Campo",
        titulo:"Domine o campo com a nova Predator Edge+",
        informacao: "Assuma o controle do jogo com a chuteira mais avançada da Predator.Texturização 3D ampliada para controle inigualável em chutes e dribles, Envolve o pé para um ajuste firme e suporte incomparável.",
        avaliação:"4.5",
        vendidos:"225",
        preço:"297,98",
    },
    {
        url: "https://www.lojadssports.com.br/cdn/shop/products/3a30367d_800x.jpg?v=1682212086",
        nome: "Adidas SpeedPortal 1.0",
        numero: 4,
        tipo: "Campo",
        titulo:"Domine o campo em todas as direções com a chuteira Adidas SpeedPortal 1.0.",
        informacao: "Uma estrutura leve e ágil que proporciona resposta instantânea a cada mudança de direção e Uma camada texturizada ultraleve que maximiza o controle da bola em alta velocidade.",
        avaliação:"4.9",
        vendidos:"316",
        preço:"381,97",
    },
    {
        url: "https://chuteiraspi.com/wp-content/uploads/2022/06/fb827122.jpg",
        nome: "Adidas SpeedFlow",
        numero: 5,
        tipo: "Campo",
        titulo:"Chuteira Adidas SpeedFlow: Liberte a sua velocidade, Seja implacável!",
        informacao: "A Chuteira Adidas SpeedFlow foi projetada para jogadores que desejam dominar a velocidade no campo. Leve, ágil e com tecnologias inovadoras, ela te permite explodir em sprints e deixar seus adversários para trás.",
        avaliação:"4.4",
        vendidos:"206",
        preço:"287,97",
        
    },
    {
        url: "https://acdn.mitiendanube.com/stores/001/805/503/products/139ea9241-6a74100e7e3e112bd416632117195533-640-0.jpg",
        nome: "Adidas Predator Edge 1",
        numero: 6,
        tipo: "Campo",
        titulo:"Domine o Jogo com a Chuteira Adidas Predator Edge 1",
        informacao: "Domine cada chute, passe e drible com a Predator Edge 1. Esta chuteira inovadora da Adidas oferece controle e potência inigualáveis, elevando seu jogo a um novo nível.",
        avaliação:"4.9",
        vendidos:"256",
        preço:"297,80",
    },
    {
        url: "https://acdn.mitiendanube.com/stores/001/055/309/products/chuteira-nike-air-zoom-mercurial-superfly-ix-elite-campo-profissional-1linha-campo-original-comprar-branca-rosa-azul-botinha-cano-confiave-11-a1a6c970314c0e151116796088230561-1024-1024.jpg",
        nome: "Nike SuperFly 9",
        numero: 7,
        tipo: "Campo",
        titulo:"Nike Superfly 9: Domine a Velocidade",
        informacao: "Desenvolvida para jogadores que redefinem o que é possível em campo, a Superfly 9 combina inovações revolucionárias com um design leve e aerodinâmico para te levar ao próximo nível.",
        avaliação:"4.7",
        vendidos:"310",
        preço:"329,98",
    },
    {
        url: "https://acdn.mitiendanube.com/stores/002/341/698/products/chuteira-campo-nike-air-zoom-mercurial-sg-cr7-2022-tevo-sports-31-124e49862fe80cd10216880667092381-1024-1024.jpg",
        nome: "Nike Air Zoom",
        numero: 8,
        tipo: "Campo",
        titulo:"Domine o Campo com a Chuteira Nike Air Zoom",
        informacao: "A Chuteira Nike Air Zoom é a arma secreta que você precisa para deixar a defesa no chão e dominar o campo. Combinando tecnologia de ponta com design inovador, essa chuteira te leva a outro nível de desempenho.",
        avaliação:"4.9",
        vendidos:"332",
        preço:"363,98",
    },
    {
        url: "https://www.cache2net2.com//Repositorio/8328/Produtos/b1aea23f-0.jpg?=1696728-1",
        nome: "Nike Super Fly",
        numero: 9,
        tipo: "Campo",
        titulo:"Desbloqueie seu potencial explosivo com a chuteira Nike Superfly.",
        informacao: "Unidade Air no calcanhar proporciona retorno de energia instantâneo a cada passo.  Leve e flexível para propulsão máxima.",
        avaliação:"4.9",
        vendidos:"220",
        preço:"297,80",
    },
    {
        url: "https://cdn.awsli.com.br/600x450/1842/1842028/produto/211027541/9c5e1c58-jbkncw.jpg",
        nome: "Nike SuperFly CR7",
        numero: 10,
        tipo: "Campo",
        titulo:"Nike SuperFly CR7: Domine o Jogo com Velocidade Explosiva",
        informacao: "Seja imparável. A Nike SuperFly CR7 é a chuteira que te leva a outro nível, impulsionando você para o topo do seu jogo. Inspirada na força e na velocidade de Cristiano Ronaldo, esta chuteira é uma obra-prima de design e tecnologia.",
        avaliação:"395",
        vendidos:"295",
        preço:"387,97",
    },
    {
        url: "https://acdn.mitiendanube.com/stores/001/055/309/products/chuteira-nike-phantom-gx-elite-fg-2023-2024-branco-com-verde-profissional-1-linha-campo-original-oficial-birro-plastico-qualidade-gramado-grama-sintetica-natural-leve-lancamento-nova-7d309d78c0624ed34d17008500867191-1024-1024.jpeg",
        nome: "Nike Phatom GX",
        numero: 11,
        tipo: "Campo",
        titulo:"Domine o campo com a Nike Phantom GX",
        informacao: "A Nike Phantom GX foi projetada para os jogadores que redefinem o jogo. Com tecnologias inovadoras e um design ousado, essa chuteira te permite dominar o campo com maestria.",
        avaliação:"4.7",
        vendidos:"236",
        preço:"256,98",
    },
    {
        url: "https://acdn.mitiendanube.com/stores/001/055/309/products/chuteira-nike-phantom-luna-elite-fg-azul-claro-com-verde-claro-profissional-1-linha-campo-original-oficial-birro-plastico-gramado-grama-sintetica-natural-lancamento-4-d1990b605882a18c8117023217236896-1024-1024.jpeg",
        nome: "Nike Phatom Luna",
        numero: 12,
        tipo: "Campo",
        titulo:"Nike Phantom Luna: Domine o campo com toque e agilidade.",
        informacao: "Desperte sua criatividade e controle o jogo com a Nike Phantom Luna. Esta chuteira inovadora foi projetada para jogadoras que ditam o ritmo, quebrando as linhas e orquestrando cada jogada com maestria.",
        avaliação:"4.9",
        vendidos:"332",
        preço:"395,98",
    },
];